config/routes.rb
Rails.application.routes.draw do
  root 'session#new'
  post '/', to: 'session#create'
  post '/sessions', to: 'session#destroy'
  post '/main_page', to: 'main_page#create'
  resources :main_page, only: [:create, :index, :prepare]
end

app/models/client.rb
class Client

  def initialize(client_response)
    @client_response = client_response
  end

  def name
    @client_response[:client_info][:name]
  end

  def email
    @client_response[:client_info][:email]
  end

  def phone
    @client_response[:client_info][:phone]
  end

  def opted_in
    @client_response[:opted_in][:result]
  end

  def found_us
    @client_response[:found_us]
  end

  def enthusiasm
    @client_response[:enthusiasm]
  end

  def timing
    @client_response[:timing]
  end

  def adopter_type
    @client_response[:adopter_type]
  end

  def stage
    @client_response[:stage]
  end
end

app/models/listing.rb
class Listing
  def initialize(listing_response)
    @listing_response = listing_response
  end

  def latitude
    @listing_response[:coordinates][:latitude]
  end

  def longitude
    @listing_response[:coordinates][:longitude]
  end

  def id
    @listing_response[:id]
  end

  def mls
    @listing_response[:mls]
  end

  def interior
    @listing_response[:home_updates][:interior]
  end

  def exterior
    @listing_response[:home_updates][:exterior]
  end

  def address_1
    @listing_response[:address][:address1]
  end

  def address_2
    @listing_response[:address][:address2]
  end

  def city
    @listing_response[:address][:city]
  end

  def state
    @listing_response[:address][:state]
  end

  def zip
    @listing_response[:address][:zip]
  end

  def baths
    @listing_response[:baths]
  end

  def beds
    @listing_response[:beds]
  end
end

app/models/pricing_estimates.rb
class PricingEstimates

  def initialize(pricing_response)
    @pricing_response = pricing_response
  end

  def zestimate
    @pricing_response[:zillow][:zestimate]
  end

  def zest_low
    @pricing_response[:zillow][:low]
  end

  def zest_high
    @pricing_response[:zillow][:high]
  end

  def hj_low
    @pricing_response[:home_junction][:low]
  end

  def hj_high
    @pricing_response[:home_junction][:high]
  end

  def hj_regional_avg
    @pricing_response[:home_junction][:regional_avg]
  end
end

app/models/property_facade.rb
require 'open-uri'

class PropertyFacade
  attr_reader :name, :attributes

  def initialize(attributes)
    @attributes = attributes
  end

  def name
    @attributes[:result][:client][:client_info][:name]
  end

  def email
    @attributes[:result][:client][:client_info][:email]
  end

  def phone
    @attributes[:result][:client][:client_info][:phone]
  end

  def map
    google_address = @attributes[:result][:listing][:id].gsub(/[_-]/, '+')
    "https://www.google.com/maps/dir/?api=1&origin=Your+location&destination=#{google_address}"
  end

  def zillow_link
    zillow_address = @attributes[:result][:listing][:id].gsub(/_/,'-')
    "https://www.zillow.com/homes/#{zillow_address}_rb/"
  end

  def opted_in
    if @attributes[:result][:client][:opted_in][:result]
      "Yes"
    else
      "No"
    end
  end

  def found_us
    @attributes[:result][:client][:found_us]
  end

  def dollars(num)
    sprintf('%.2f',num).gsub('.00','').reverse.scan(/(\d*\.\d{1,3}|\d{1,3})/).join(',').reverse.prepend('$')
  end

  def zestimate
    dollars (@attributes[:result][:pricing_estimates][:zillow][:zestimate])
  end

  def z_low
    dollars(@attributes[:result][:pricing_estimates][:zillow][:low])
  end

  def z_high
    dollars(@attributes[:result][:pricing_estimates][:zillow][:high])
  end

  def hj_low
    dollars(@attributes[:result][:pricing_estimates][:home_junction][:low])
  end

  def hj_high
    dollars(@attributes[:result][:pricing_estimates][:home_junction][:high])
  end

  def hj_avg
    dollars(@attributes[:result][:pricing_estimates][:home_junction][:regional_avg])
  end

  def enthusiasm
    @attributes[:result][:client][:enthusiasm]
  end

  def timing
    @attributes[:result][:client][:timing]
  end

  def adopter_type
    @attributes[:result][:client][:adopter_type]
  end

  def updates
    @attributes[:result][:listing][:home_updates].values
  end

  def stage
    @attributes[:result][:client][:stage]
  end

  def retainer
    500
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :auth_token

  def auth_token
    session[:user]
  end
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  before_action :check_login

  def index
  end

  def create
    if params[:address] && ! params[:address].include?('_')
      address = AddressFormatter.new(params[:address]).formatter
      api_call = PropertyService.new(address, auth_token)
      facade_raw_data = api_call.response
      facade_raw_data = JSON.parse(facade_raw_data.to_json, symbolize_names: true)
      @property_facade = PropertyFacade.new(facade_raw_data)
      render :prepare
    elsif params[:credit_card]
      appointment_info = {consultation: {
        :address => address,
        :about_this_home => params[:about_this_home],
        :client_enthusiasm => params[:client_enthusiasm],
        :commission => params[:commission],
        :about_the_seller => params[:about_the_seller],
        :credit_card => params[:credit_card],
        :exp_date => params[:exp_date][:exp_date_2],
        :price => params[:price],
        :start_time => params[:start_time],
        :end_time => params[:end_time]
      }}
      AppointmentCollector.new(appointment_info, auth_token, params[:email])
      facade_raw_data = eval(params["attributes"])
      @property_facade = PropertyFacade.new(facade_raw_data)
      render :prepare
    else
      flash.now[:error] = "That address does not exist/is incomplete. Please try again."
      render :index
    end
  end
  private

  def check_login
    redirect_to '/' unless session[:user]
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def destroy
    session[:user] = nil
    redirect_to '/'
  end

  def create
    check_login
    result = MembersService.new(params[:user][:address], params[:password])
    if result.success
      session[:user] = result.success
      session[:email] = params[:user][:address]
      redirect_to main_page_index_path(request.parameters)
    else
      flash.now[:error] = result.error
      render :new
    end
  end



  private
  def check_login
    redirect_to '/main_page' if session[:user]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeConsultant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins|Questrial" rel="stylesheet">
  </head>

  <body>
    <%= yield %>

    <div class="flash">
      <% flash.each do |type, message| %>
      <%= content_tag :div, sanitize(message), class: type %>
      <% end %>
    </div>

    <script src="/assets/javascripts/scripts.js"></script>
  </body>
</html>

app/views/main_page/index.html.erb
<div class="header-text">
  <h3><b>Pricing Location Address</b></h3>
</div>

<div class="location_form">
  <%= form_tag("/main_page", method: "post") do %>
    <div class="label">
      <%= label_tag(:location_address, "Please fill in the complete address.") %>
    </div>
    <div class="input-field">
      <%= text_field_tag(:address) %>
    </div>
    <%= hidden_field_tag(:email, "#{@email}") %>
    <div class="submit-button">
      <%= submit_tag("Find Location", class: "find-location-button") %>
    </div>

    <p class="message"></p>
  <% end %>
  <div class="logout">
    <%= link_to "Log Out", sessions_path, method: 'post', class: "log-out-button" %>
  </div>
</div>

app/views/main_page/prepare.html.erb
<div class="find-section">
  <div class="container-fluid">
    <div class="address_preparation container-fluid">
      <div class="header-text">
        <h3><b>Client Details</b></h3>
      </div>
      <div class="field_headers">
        <div class="row">
          <div class="col-4">
            <p><b>Name: </b></p>
          </div>
          <div class="col-8">
            <p><%= @property_facade.name %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p><b>Email: </b></p>
          </div>
          <div class="col-8">
            <p><%= mail_to @property_facade.email  %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p><b>Phone: </b></p>
          </div>
          <div class="col-8">
            <p><%= link_to @property_facade.phone, "tel:#{@property_facade.phone}"  %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p><b>Opted In: </b></p>
          </div>
          <div class="col-8">
            <p><%= @property_facade.opted_in %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p><b>Found Us: </b></p>
          </div>
          <div class="col-8">
            <p><%= @property_facade.found_us %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p><b>Map: </b></p>
          </div>
          <div class="col-8">
            <p><a href="<%= @property_facade.map %>">Click for Directions to Property</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="estimate-types container-fluid">
      <div class="header-text">
        <h3><b>Estimates</b></h3>
      </div>
      <div class="estimate-block">
        <h4 class="estimate_header"><b><a href="<%= @property_facade.zillow_link %>">Zillow</a></b></h4>
        <div class="row">
          <div class="col-4">
            <p><b>Zestimate: </b></p>
          </div>
          <div class="col-8">
            <p><%= @property_facade.zestimate %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p><b>Low: </b></p>
          </div>
          <div class="col-8">
            <p><%= @property_facade.z_low %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p><b>High: </b></p>
          </div>
          <div class="col-8">
            <p><%= @property_facade.z_high %></p>
          </div>
        </div>
        <h4 class="estimate_header"><b>Home Junction</b></h4>
        <div class="row">
          <div class="col-4">
            <p><b>Low: </b></p>
          </div>
          <div class="col-8">
            <p><%= @property_facade.hj_low %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p><b>High: </b></p>
          </div>
          <div class="col-8">
            <p><%= @property_facade.hj_high %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p><b>Regional Avg: </b></p>
          </div>
          <div class="col-8">
            <p><%= @property_facade.hj_avg %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="client-partnership-indicators container-fluid">
      <div class="header-text">
        <h3><b>Client Partnership Indicators</b></h3>
      </div>
      <div class="indicator-details">
        <div class="row">
          <div class="col-4">
            <p><b>Enthusiasm: </b></p>
          </div>
          <div class="col-8">
            <p><%= @property_facade.enthusiasm %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p><b>Timing: </b></p>
          </div>
          <div class="col-8">
            <p><%= @property_facade.timing %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p><b>Adopter Type: </b></p>
          </div>
          <div class="col-8">
            <p><%= @property_facade.adopter_type %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p><b>Stage: </b></p>
          </div>
          <div class="col-8">
            <p><%= @property_facade.stage %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p><b>Retainer: </b></p>
          </div>
          <div class="col-8">
            <p>$<%= @property_facade.retainer %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="client-updates container-fluid">
      <div class="header-text">
        <h3><b>Client Updates</b></h3>
      </div>
      <div class="update-list">
        <% @property_facade.updates.each do |update| %>
          <p class="update"><%= update %></p>
        <% end %>
      </div>
    </div>
    <!-- Button trigger modal -->
    <div class="button-spacing">
      <button type="button" id="start_timer" class="start-button" data-toggle="modal" data-target="#exampleModalLong" onclick="startTimer()">
        Start Consultation
      </button>
    </div>
  </div>
</div>

<div class="logout">
  <%= link_to "Log Out", sessions_path, method: 'post', class: "log-out-button" %>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Consultation Details</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body modal-form">
        <div class="collect-data">
          <%= form_tag("/main_page", method: "post") do %>
            <%= label_tag(:about_the_home, "About the Home") %>
            <%= text_area_tag(:about_this_home) %>
            <%= label_tag(:recommended_price, "Recommended List Price") %>
            <%= text_field_tag(:price) %>
            <%= label_tag(:update_enthusiasm, "Update Client Enthusiasm", class: "display-block") %>
            <%= select_tag(:client_enthusiasm, options_for_select([['Mild', 1], ['Medium', 2], ['Spicy', 3]]))%>
            <%= label_tag(:buyer_agent_comm, "Buyer Agent Commission", class: "display-block") %>
            <%= text_field_tag(:commission) %>
            <%= label_tag(:about_seller, "About the Seller", class: "display-block") %>
            <%= text_area_tag(:about_the_seller) %>
            <%= label_tag(:credit_number, "Credit Card Number", class: "display-block") %>
            <%= password_field_tag(:credit_card) %>
            <%= label_tag(:credit_expiration, "Credit Card Expiration Date") %>
            <%= hidden_field_tag(:attributes, "#{@property_facade.attributes}") %>
            <%= month_field(:exp_date, :exp_date_2) %>
            <%= hidden_field_tag :start_time %>
            <%= hidden_field_tag :end_time %>
        </div>
      </div>
      <div class="modal-footer">
        <p class="message"></p>
        <button type="button" class="log-in-submit" data-dismiss="modal">Close</button>
        <%= submit_tag('Save',id: "stop_timer", onclick: "stopTimer()", class: 'btn save-button', style: "color: #96C93D; background-color: #000000; width: 90px; height: 40px; border-radius: 20px;") %>
         <% end %>
      </div>
    </div>
  </div>
</div>

<div class="collect_form">
<script type="text/javascript">
function startTimer() {
 var startTime = Date.now()
      $("#start_time").val(startTime);
}
function stopTimer() {
  var endTime = Date.now()
  $("#end_time").val(endTime)
}
</script>

app/views/session/new.html.erb
<%= image_tag("TRELORA-Logo-.png", class: "center zoom")%>

<div class="header-text">
  <h3><b>Home Consultant</b></h3>
</div>

<div class="log-in-form">
  <%= form_tag("/", method: "post") do %>
    <div class="label">
      <%= label_tag(:member_email, "Member Email") %>
    </div>
    <div class="input-field">
      <%= email_field(:user, :address) %>
    </div>
    <div class="label">
      <%= label_tag(:password) %>
    </div>
    <div class="input-field">
      <%= password_field_tag(:password) %>
    </div>

    <div class="submit-button">
      <%= submit_tag("Log in", class: "log-in-submit") %>
    </div>

  <p class="message"></p>
  <% end %>
</div>